import type { Metadata } from "next";
import "./style/global.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {/* {children} */}
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
