import type { Metadata } from "next";
import "./style/global.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { themeConfig } from './style/theme.js';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body>
				{/* {children} */}
				<ConfigProvider theme={themeConfig}>
					<AntdRegistry>{children}</AntdRegistry>
				</ConfigProvider>
			</body>
		</html>
	);
}
